### ISSUE TITLE
Correlation between compiled main.js, magento module and compiled package

### ISSUE THREAD

**Issue by bacciproductions** [phuhung273/solpay-js#1]
Thanks for putting this together! 

I was able to compile the main.js, change my sol address and the button shows in checkout on my test site (haven't tried a transaction yet).

I'm wondering how you chose the correct dependencies in the "my-webpack-project" package-lock.json? 

I looked at the Solana Solpay package-lock.json and it has 12764 lines vs the "my-webpack-project's" 8145 lines.

In the future, to keep the solpay magento module's main.js package current will it need more than running the npm updates? 
Will the dependencies need to be updated and is there a source for where to get the current needed dependencies? 

Been waiting for a Solpay module to pop up so i could try it, thanks for putting this together!

**Comment by phuhung273** [comment]
`package-lock.json` might be different because of many reasons:
- They use different dependencies
- Their node version is different. Mine was `node 18`

These solana libraries are just wrappers on calling solana APIs. Such APIs would definitely be updated in the future. So yes, it will take more effort than just npm updates.

For this project, I simply installed every newest packages. If something goes wrong, I think we should copy dependencies from those popular projects.

**Comment by bacciproductions** [comment]
Awesome, thanks for the answer @phuhung273 . You can close this ticket and thanks again for creating this extension!
